name: Deployment Pipeline
on:
  push:
    branches: [main]
env:
  ENV: qa
  ENV_FILE: ./environments/qa.tfvars
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '22'
      - run: npm ci
      - run: npm test
      
  terraform-qa:
    runs-on: ubuntu-latest
    environment: $ENV
    defaults:
      run:
        working-directory: ./infrastructure

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.10.5" 
        
      - name: Install pre-commit
        run: |
          pip install pre-commit
          pre-commit install

      - name: Install ShellCheck
        run: sudo apt-get install -y shellcheck
          
      - name: Install tflint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
          
      - name: Run pre-commit checks
        run: pre-commit run --all-files
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        
      - name: Terraform Plan
        if: github.event_name == 'pull_request'
        working-directory: infrastructure/dynamodb
        run: |
          terraform init -backend-config="key=$ENV/terraform.tfstate"
          terraform plan -var-file="${GITHUB_WORKSPACE}/infrastructure/dynamodb/environments/$ENV.tfvars" -out=terraform.tfstate
        
          
  deploy-qa:
    needs: [terraform-qa]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '22'
      - name: Push to QA Branch
        env:
          GITHUB_TOKEN: ${{ secrets.TRIPS_TOKEN }}
        run: |
          git checkout -B qa main
          git push -f https://$GITHUB_TOKEN@github.com/${{ github.repository }} qa
                      
      - name: Deploy to QA
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          npm i -g vercel
          vercel deploy --token $VERCEL_TOKEN --env ENVIRONMENT=qa
          


