name: Deployment Pipeline
on:
  push:
    branches: [main]
  # pull_request:
  #   branches: [main]
env:
  ENV: qa
  ENV_FILE: ./environments/qa.tfvars
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '22'
      - run: npm ci
      - run: npm test
      
  deploy-qa-infrastructure:
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Terraform Apply
        if: github.ref == 'refs/heads/develop'
        working-directory: infrastructure/dynamodb
        run: |
          terraform init -backend-config="key=$ENV/terraform.tfstate"
          terraform plan -var-file="${GITHUB_WORKSPACE}/infrastructure/dynamodb/environments/$ENV.tfvars" -out=terraform.tfstate
          terraform apply -auto-approve -var-file="${GITHUB_WORKSPACE}/infrastructure/dynamodb/environments/$ENV.tfvars" terraform.tfstate
      
  deploy-qa:
    needs: [deploy-qa-infrastructure]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '22'
      - name: Push to QA Branch
        env:
          GITHUB_TOKEN: ${{ secrets.TRIPS_TOKEN }}
        run: |
          git checkout -B qa main
          git push -f https://$GITHUB_TOKEN@github.com/${{ github.repository }} qa
                      
      - name: Deploy to QA
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          npm i -g vercel
          vercel deploy --token $VERCEL_TOKEN --env ENVIRONMENT=qa
          


