name: Deployment Pipeline
on:
  push:
    branches: [prod]
env:
  ENV: prod
  ENV_FILE: ./environments/prod.tfvars
  PROD_BRANCH: prod
jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '22'
      - run: npm ci
    #   - run: npm run test:integration
    #  add this later
        env:
          QA_URL: ${{ needs.deploy-qa.outputs.url }}

  deploy-prod-infrastructure:
    needs: integration-tests
    if: github.ref == 'refs/heads/$PROD_BRANCH'
    runs-on: ubuntu-latest
    steps:
      - name: Terraform Apply
        if: github.ref == 'refs/heads/develop'
        working-directory: infrastructure/dynamodb
        run: |
          terraform init -backend-config="key=$ENV/terraform.tfstate"
          terraform plan -var-file="${GITHUB_WORKSPACE}/infrastructure/dynamodb/environments/$ENV.tfvars" -out=terraform.tfstate
          terraform apply -auto-approve -var-file="${GITHUB_WORKSPACE}/infrastructure/dynamodb/environments/$ENV.tfvars" terraform.tfstate

  deploy-prod:
    needs: [deploy-prod-infrastructure]
    runs-on: ubuntu-latest
    environment: 
      name: production
      url: https://mtp.weekendwanderings.com
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '22'
      - name: Deploy to Production
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          npm i -g vercel
          vercel deploy --prod --token $VERCEL_TOKEN --env ENVIRONMENT=production